# Generated by Django 2.0.5 on 2018-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='nationality',
            field=models.IntegerField(choices=[('FR', 'France'), ('US', 'Etats-Unies')], null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='media',
            name='originale_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre original'),
        ),
        migrations.AlterField(
            model_name='media',
            name='pegi_certification',
            field=models.IntegerField(null=True, verbose_name='Certification'),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='media',
            name='synopsis',
            field=models.TextField(null=True, verbose_name='Synopsis'),
        ),
    ]
